version: "3.8"

services:
  db:
    image: mcr.microsoft.com/azure-sql-edge:latest
    container_name: eviction_sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "StrongPassword1"
    ports:
      - "1433:1433"
    volumes:
      - ./SQLData:/var/opt/mssql
    healthcheck:
      test: [ "CMD", "/opt/mssql-tools/bin/sqlcmd", "-S", "localhost", "-U", "sa", "-P", "StrongPassword1", "-Q", "SELECT 1" ]
      interval: 10s
      timeout: 5s
      retries: 30

  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    working_dir: /rails
    volumes:
      - .:/rails
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      RAILS_ENV: development
      DB_ADAPTER: sqlserver
      DB_HOST: db
      DB_PORT: 1433
      DB_USERNAME: sa
      DB_PASSWORD: StrongPassword1
